---
title: "Evaluates effect size thresholding"
author: "Simon Vandekar"
date: "10/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::knit_hooks$set(GPs=function(before, options, envir){
  if (before){
    cex=1.5
    # graphical parameters
    fgcol = 'white'
    bgcol = 'black'
    par(mgp=c(0.9,.7,0), lwd=1.5, lend=2,
        cex.lab=cex, cex.axis=0.8*cex, cex.main=1*cex,
        mar=c(0.5,2.2,2,0), bty='l', oma=c(0,0,2,0), bg=bgcol, fg=fgcol, col.axis=fgcol, col.lab=fgcol, col.main = fgcol, col.sub=fgcol)
  }})
knitr::opts_chunk$set(echo = FALSE, fig.height = 4, fig.width = 4, GPs=TRUE, cache=TRUE, cache.lazy=FALSE)
path = Sys.getenv('PATH')
path = Sys.setenv('PATH'=paste(path, '/home/rstudio/.local/bin', sep=':'))
set.seed(555)
```


## Setup simulations

```{r simsetup}
# install the latest versions of the packages to perform these analyses.
devtools::install_github('simonvandekar/pbj', ref='inference')
devtools::install_github('statimagcoll/NIsim', ref='master')

### LIBRARIES ###
library(RNifti)
library(parallel)
library(splines)
library(progress)
library(pbj)
library(NIsim)

### DATA LOCATION ###
datadir = '/media/disk2/pbj/data'
# will be created by downloadABIDE
dbimagedir = file.path(datadir, 'abide/neuroimaging/cpac/alff')
templatefile = file.path(datadir, 'abide/neuroimaging/MNI152_T1_3mm.nii.gz')
# created by simSetup... Not used in this analysis
dbresimagedir = file.path(datadir, 'abide/neuroimaging/cpac/alff_res')
# created below
maskfile = file.path(datadir, 'abide/neuroimaging/cpac/mask.nii.gz')
#dbdatafile = '~/pbj/data/abide/demographic/n1035_phenotypic_20190509.rds'
#dbimagedir = '~/pbj/data/abide/neuroimaging/cpac/alff_cropped/'
#dbresimagedir = '~/pbj/data/abide/neuroimaging/cpac/alff_cropped_res/'
#maskfile = '~/pbj/data/abide/neuroimaging/cpac/cropped_n1035_mask.nii.gz'

# load in data and get directories
dat = downloadABIDE(datadir)
# some data curation is done on download. Subset all pass on visual inspection and making sex and dx factors, remove rows with no file name
dat$imgname = paste(dat$file_id, 'alff.nii.gz', sep='_')
dat$files = file.path(dbimagedir, dat$imgname)


  imgs = simplify2array(readNifti(dat$files) )
  # choose
  # number of people with zeros at that location
  inds=numeric()
  ids = c()
  subids = dat$sub_id
  # number of voxels with no zeros
  nnzero = 0
  # iteratively removes subjects who will increase the mask the largest
  while(nnzero<30000){
    voxSums = rowSums(imgs==0, dims=3)
    tab = as.data.frame(table(voxSums))
    nnzero=tab[1,2]
    # number of unique voxels for each subject
    uniquevox = apply(imgs, 4, function(img) sum(img==0 & voxSums==1) )
    # number of subjects to remove based on those subjects decreasing the amount of unique zero voxels by 50%
    #ind = which(cumsum(sort(uniquevox[ uniquevox>0], decreasing = TRUE))/tab$Freq[2]>0.5)[1]
    #inds = which(uniquevox>=sort(uniquevox, decreasing = TRUE)[ind])
    inds = which.max(uniquevox)
    cat('\nIteration:\nsubject removed: ', paste(subids[inds], collapse=', '), '\nmask size is now ', nnzero+sum(uniquevox[inds]), '\nNumber of voxels added:', sum(uniquevox[inds]) )
    imgs = imgs[,,,-inds]
    subids = subids[-inds]
    nnzero=nnzero+sum(uniquevox[inds])
  }
  nexcluded = nrow(dat) - length(subids)
  cat('\nExcluded', nexcluded, 'subjects.')
  #tab$cumvox = rev(cumsum(rev(tab$Freq)))
  dat = dat[ dat$sub_id %in% subids,]
  
  # now create the mask
  mask = readNifti(dat$files[1])
  imgs = simplify2array(readNifti(dat$files) )
  # mask actually still has pretty low coverage
  mask[,,] = 0
  mask[,,] = apply(imgs>0, 1:3, all)
  writeNifti(mask, maskfile)
  nvox = sum(mask)
  rm(imgs)
```

`r nexcluded` subjects excluded for low coverage. `r nrow(dat)` subjects in the data set. There are `r nvox` voxels in the mask.

# Fit ABIDE
Fit the model and run a few bootstraps in the ABIDE data.
```{r, simconfig}

lmfull = paste0(" ~ sex + func_mean_fd + dx_group + ns(age_at_scan, df=3)" )
lmred = paste0(" ~ sex + func_mean_fd + dx_group + age_at_scan")
nboot=2

dat = dat[!apply(is.na(as.matrix(dat[, all.vars(as.formula(lmfull))]) ), 1, any) ,]
robustStatmap = lmPBJ(dat$files, form=lmfull, formred=lmred, mask=mask, data=dat, transform = 'none', HC3 = TRUE, robust=TRUE )

test = pbjInference(robustStatmap, nboot = nboot, method = 't')

```


